image: ghcr.io/vioneta/{arch}-hassio-supervisor
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.20
  armhf: ghcr.io/home-assistant/armhf-base-python:3.12-alpine3.20
  armv7: ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.20
  amd64: ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.20
  i386: ghcr.io/home-assistant/i386-base-python:3.12-alpine3.20
# codenotary:
#   signer: notary@home-assistant.io
#   base_image: notary@home-assistant.io
# cosign:
#   base_identity: https://github.com/home-assistant/docker-base/.*
#   identity: https://github.com/home-assistant/supervisor/.*
args:
  COSIGN_VERSION: 2.4.0
labels:
  io.hass.type: supervisor
  org.opencontainers.image.title: Vioneta Agro Supervisor
  org.opencontainers.image.description: Container-based system for managing Vioneta Agro Core installation
  org.opencontainers.image.source: https://github.com/Vioneta/supervisor
  org.opencontainers.image.authors: The Vioneta Agro Authors
  org.opencontainers.image.url: https://www.vioneta.com/
  org.opencontainers.image.documentation: https://www.vioneta.com/docs/
  org.opencontainers.image.licenses: Apache License 2.0
